os:
  - linux

language: c

sudo: required

services:
  - docker

install:
  - docker pull jchodera/omnia-build-box

script:
  - docker run -e ANACONDA_TOKEN -t -i --rm -v
      `pwd`:/io jchodera/omnia-build-box:latest
      bash /io/devtools/docker-build.sh

env:
  global:
    secure: "pBu2Os5HoKm/0di32kazLVCDPEM1i/0iS2UG42RhZTgxlliILXRrQL7B5NtRUNXkPIuc/753U0h5A/xRPcmh9u7Wj8KpxqkxF3r8+z21i14VCP6MPSvVKb60FNgdMLvAWhcmtSfkR5/iynorSExxyK2aDJh/ymp3OPDrlzrF+O2hCqQKbnDYoEWoVwDZnKsQg0hwOBPgv/YfnBdikOyFFpGPyeC/hjPoPqz3x1lUf4tF7bf/0Kc9qHS7WVOM29SAGO2UFXi+1wfQsbQs8KqigjxxIO4aKTJ7x0p0DnJchVPbHMXbWlZRNceVuhGEQ28BxDX9dkp6tXYR3cmzYY5g+pRK4EG+J21DyRLE+q8R1IVnA7C1sCFxAijiR/vX+d+Bij3FzdUODQ68xFuMbiN7shWbn+XljN6JoYe90u2gWX137HXQYpGdTUUCuF0sV2zJb3DxuuZKdirVa9p79eC/N3JS2CkU2/AZllSlW7mIYtO4Av9sLAH3kmLZVfFHY+oagcFTGGfZ5kWRq4TX+ENOzeUt55/zfOOYSWBeU7na5tkjPfCv53fOByDlPCPV4+tTRnPmOlOptxmid19ZlsijvoU4NrtWDxp0WrLKlpExmZCIsTIr3iktlUz1njGpFX0E3ZakHZfJ/NSc60lN1eqTPMviPBD/1aMgEUYXVB7UCJc="
