os:
  - linux

language: c

sudo: required

services:
  - docker

install:
  - docker pull jchodera/omnia-build-box

script:
  - docker run -e ANACONDA_TOKEN -t -i --rm -v
      `pwd`:/io jchodera/omnia-build-box:latest
      bash /io/devtools/docker-build.sh

env:
  global:
    secure: "OsfVlba1JnIJAA1HM84dDgQPFcfW7aZl+cv2b6sZCMKmSp3KHSU+epMUIho6Y/mbf8m3FQAY+9VYI/cYaxVGx8c1NzKeGRFaIGLnA5CmCPOk8+LRFM+fNlb4YZjaIecR3TfUY8Y5kj+ma9OweVWiWECdNIX5yZ9uVyxAk3Vfts/QxRTo8kdDVTIVfbEfASGMaZ5shpNh7XThAStVWxPSy4LwogoVz6Wl9cK6IEymWLJScZ53rwpyVMG70NkAzH4J17u4GzrI8P7dsXSimWfy6qSoE9VdA+fHAcbyznYxmFJOXDM81zt2g4ayQ2REtweeJIOrUtJEuBLuXP8XxEb3w5UQWH3W4honA/iFyaSQ7xUnKS6lB8lLVQaxEAK3iOrNeTYtMvyXF1R4Bjk4yKSBAkZhwrQlX9cM8tehh2lVYJENzhcwZ55R8E2sJXre4OKlki7jNY7f9NMVyd4reC1UrfYQaAgiX1BtLrmEVXLWOZpEDp4zP0Yk4q+CLP22aUNi7jUDUVK8tCRwIbmCjuO+nbA/xsDU9/mhX2WCXgp8PHlG6FO4xtrTkZZg09M6bv94dnb7/7IyKEjWB88/29jRiec5ZaWCXTZNJBoqho5YxQbkBWd7GjpyfnjIdQR+2s71L6jd8w/DKCw9kUXu4cZxCURVWKGhAC5SAMu5BqgApvk="
