os:
  - linux

language: c
sudo: required

services:
  - docker

install:
  - docker pull jchodera/omnia-build-box

script:
  - docker run -t -i --rm -v `pwd`:/io
           jchodera/omnia-build-box:latest
           bash /io/devtools/docker-build.sh