package:
  name: meld-plugin-test
  version: {{ environ['GIT_DESCRIBE'] }}


source:
  path: /io

requirements:
  build:
    - cmake
    - python
    - swig ==3.0.7
    - openmm-dev
    - eigen3

  run:
    - python
    - openmm-dev

test:
  imports:
    meld-plugin

about:
    home: https://github.com/maccallumlab/meld-openmm-plugin
    
