package:
  name: meld-test
  version: "0.0.0"


source:
  path: /io

requirements:
  build:
    - cmake
    - python
    - swig ==3.0.7
    - openmm-dev
    - eigen3

  run:
    - python
    - openmm-dev
