package:
  name: meld-test
  version: {{ environ['VERSTRING'] }}


source:
  path: /io # [linux]
  path: /Users/travis/build/maccallumlab/meld #[osx]

requirements:
  build:
    - python
    - numpy
    - scipy
    - hdf4
    - netcdf4
    - openmm
    - meld-plugin-test
    - sphinx
    - mock
    - six
    - sphinx_rtd_theme ==0.1.9

  run:
    - ambermini
    - python
    - openmm
    - meld-plugin-test
    - numpy
    - scipy
    - hdf4
    - netcdf4
    - mock
    - six

test:
  imports:
    - meld
  commands:
    - python -m unittest discover meld.test

about:
    home: https://meldmd.org
