package:
  name: meld-test
  version: {{ environ['VERSTRING'] }}


source:
  path: /io

requirements:
  build:
    - python
    - numpy
    - scipy
    - netcdf4
    - openmm-dev
    - meld-plugin
    - sphinx
    - mock
    - six
    - sphinx_rtd_theme ==0.1.9

  run:
    - python
    - openmm-dev
    - meld-plugin
    - numpy
    - scipy
    - netcdf4
    - mock
    - six

test:
  imports:
    - meld

about:
    home: https://meldmd.org
